version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tiramisu
    networks:
      - springapimysql-net  
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: app
    depends_on:
      - mysqldb
    build: 
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - springapimysql-net
    environment:
      - database=mysqldb
      - password=root
    ports:
      - 8082:8082
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:

networks:
  springapimysql-net:
    driver: bridge
