version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tiramisu
    networks:
      - springapimysql-net  
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  springboot:
    container_name: springboot
    depends_on:
      - mysqldb
    build: 
      dockerfile: backend/Dockerfile
    restart: on-failure
    networks:
      - springapimysql-net
    ports:
      - 8082:8082
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  angular-front:
    container_name: angular-front
    depends_on:
      - springboot
    build: 
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - springapimysql-net

volumes:
  db:

networks:
  springapimysql-net:
    driver: bridge
